### ISSUE TITLE
Error: line 22: unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by chadsaun** [mirzakhany/install-helm-action#1]
When using:
```
      - name: Install Helm & Kubectl
        uses: mirzakhany/install-helm-action@v1
        with:
          k8s_config: ${{ env.KUBECONFIG }}
```

I get this error:
```
/runner/_work/_temp/18b78127-77d5-4192-8969-3f5d6c74672f.sh: line 22: unexpected EOF while looking for matching `"'
Error: Process completed with exit code 2.
```
